---
- name: create user group
  group: name=wp state=present

- name: add ubuntu to wp
  user: name=ubuntu append=yes groups="adm,wp"

- name: Create www-data user
  user: name={{wp_user}} append=yes groups="adm,wp" shell=/bin/bash

- name: upload sudoers.d file
  copy: src=sudoers-admin dest=/tmp/admin-sudo owner=root group=root mode=0440

- name: move file to sudoers.d
  shell: visudo -q -c -f /tmp/admin-sudo && cp /tmp/admin-sudo /etc/sudoers.d/admin-sudo

- name: install apt requirements
  apt: pkg={{item}} state=present update_cache=yes install_recommends=yes
  with_items:
    - mysql-client-5.5
    - mysql-common
    - php5-common
    - php5-mysql
    - apache2
    - apache2-utils
    - apache2.2-common
    - libapache2-mod-php5
    - python-mysqldb
    - unzip
    - php5-curl
  notify: restart apache

- name: setup mysql database
  mysql_db: db={{database_name}} state=present login_host={{database_host}} login_password={{database_root_password}} login_user={{database_root_user}}

- name: setup mysql user
  mysql_user: name={{database_user}} password={{database_password}} priv={{database_name}}.*:ALL state=present login_host={{database_host}} login_password={{database_root_password}} login_user={{database_root_user}} host=%
  when: database_host not in ["localhost", "127.0.0.1"]

- name: setup mysql user
  mysql_user: name={{database_user}} password={{database_password}} priv={{database_name}}.*:ALL state=present login_host={{database_host}} login_password={{database_root_password}} login_user={{database_root_user}}
  when: database_host in ["localhost", "127.0.0.1"]


- name: create www directory if needed
  file: path={{app_base_dir}} state=directory

- name: download wordpress
  get_url: url=http://wordpress.org/latest.tar.gz dest={{app_base_dir}}/{{site_name}}.tar.gz mode=0764

- name: untar wordpress
  shell: tar -xzvf {{site_name}}.tar.gz creates=${app_base_dir}/wp-created chdir=${app_base_dir}

- name: create lock file
  copy: src=lockfile dest=${app_base_dir}/wp-created owner=www-data group=wp mode=0644

#The creates keyword does not always seem to work, and sometimes the command after this will try to run and fail
- name: add wordpress directory
  file: path={{app_base_dir}}/wordpress state=directory

#Required for the multisite domain mapping to work
- name: move files from wordpress directory to top level dir
  shell: cp -r {{app_base_dir}}/wordpress/* {{app_base_dir}} chdir={{app_base_dir}}/wordpress creates=${app_base_dir}/wp-moved

- name: create lock file
  copy: src=lockfile dest=${app_base_dir}/wp-moved owner=www-data group=wp mode=0644

- name: remove wordpress directory
  file: path={{app_base_dir}}/wordpress state=absent

- name: render wp-config.php from template
  template: src=wp-config.php.j2 dest={{app_base_dir}}/wp-config.php owner=root group=root mode=0644

- name: create directory for xcloner backup admin
  file: path={{app_base_dir}}/administrator/backups state=directory owner=root group=wp mode=2775

- name: create directory for xcloner backup
  file: path={{app_base_dir}}/xcloner-backups state=directory owner=root group=wp mode=2775

- name: change ownership on files in wordpress directory to wp_user
  shell: chown -R {{wp_user}}:wp {{app_base_dir}}

- name: change ownership on wordpress directory to root
  shell: chown root:root {{app_base_dir}}

- name: create apache directory and set perms
  file: path=/etc/apache2/sites-available owner=root group=wp mode=2775 state=directory

- name: enable apache mod_rewrite
  shell: sudo a2enmod rewrite
  notify: restart apache

- name: Removing default apache config
  file: path=/etc/apache2/sites-enabled/default state=absent
  notify: restart apache

- name: render apache sites available
  template: src=apache-wp.j2 dest=/etc/apache2/sites-available/{{site_name}}
  notify: restart apache

- name: Creating config link to sites available
  file: src=/etc/apache2/sites-available/{{site_name}} dest=/etc/apache2/sites-enabled/{{site_name}} state=link owner=root group=root
  notify: restart apache

- name: disable default site
  shell: a2dissite default

- name: enable wordpress site
  shell: a2ensite {{site_name}}





